# Site settings
title: Duang
email: duang@duangduang.us
description: > # this means to ignore newlines until "baseurl:"
  Duang : Chinese Technology Culture
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://duangduang.us" # the base hostname & protocol for your site
twitter_username: duangduang
github_username:  duangduang

# Build settings
markdown: kramdown
